import { ITINERARY } from '../data/trip/itinerary.js';
import { DAILY_BUDGET } from '../data/trip/daily-budget.js';
import { FOODS } from '../data/trip/foods.js';
import { SHOPPING } from '../data/trip/shopping.js';
import { RESORT_ACTIVITIES } from '../data/trip/resort.js';
import { MEMBERS } from '../data/trip/members.js';
import { ROOMS } from '../data/trip/rooms.js';
import { VERSION } from '../data/system/version.js';
import { AIRPORT_TRANSFER } from '../data/trip/airport-transfer.js';
import { DIGITAL_GUIDE } from '../data/trip/guide.js';
import { MAP_LOCATIONS, MAP_CATEGORIES } from '../data/trip/map-locations.js';
import { ANNOUNCEMENTS, ANNOUNCEMENT_TYPES } from '../data/trip/announcement.js';
import { CHECKIN_DAYS, CHECKIN_STATUS } from '../data/trip/checkin.js';

const state={lang:localStorage.getItem('mtc-lang')||'zh',day:1,hotel:'lexis',guideCategory:null,guideQuery:'',mapCategory:'all',mapDay:0,mapQuery:'',mapInstance:null,mapMarkers:[],userPosition:null,noticeFilter:'all',noticeEditor:false,checkinDay:1,checkinQuery:'',checkinFilter:'all'};
const t=(zh,vi)=>state.lang==='zh'?zh:vi;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const routes=['home','itinerary','budget','food','shopping','resort','traveler','rooms','guide','map','notifications','checkin'];
function route(){const r=(location.hash.replace('#/','')||'home').split('?')[0];return routes.includes(r)?r:'home'}
function header(){return `<div class="topbar"><div class="brand"><div class="brand-mark">🇲🇾</div><div><b>${t('馬來西亞手帳 2026','Sổ tay Malaysia 2026')}</b><small>國能員旅 · Release v3.4</small></div></div><button class="lang" id="langBtn">${state.lang==='zh'?'VI':'中'}</button></div>`}
function nav(active){const items=[['home','🏠',t('首頁','Trang chủ')],['itinerary','🗓️',t('行程','Lịch trình')],['budget','💰',t('費用','Chi phí')],['traveler','👥',t('團員','Thành viên')],['guide','📖',t('手冊','Cẩm nang')],['map','🗺️',t('地圖','Bản đồ')],['notifications','🔔',t('通知','Thông báo')],['checkin','✅',t('簽到','Điểm danh')]];return `<nav class="nav"><div class="nav-inner">${items.map(([r,i,l])=>`<a href="#/${r}" class="${active===r?'active':''}"><i>${i}</i>${l}</a>`).join('')}</div></nav>`}
function shell(content,active){return `<div class="shell">${header()}<main>${content}<div class="version">Release ${VERSION.version} · ${VERSION.build}</div></main>${nav(active)}</div>`}
function home(){return shell(`<section class="hero"><span class="pill">✈️ 2026/09/20–09/24</span><h1>${t('馬來西亞五日員工旅遊','Du lịch Malaysia 5 ngày')}</h1><p>${t('行程、房間、機位、每日費用、美食與伴手禮一次整理。','Tổng hợp lịch trình, phòng, chỗ ngồi, chi phí, ẩm thực và quà tặng.')}</p></section><div class="grid stats" style="margin-top:12px"><div class="card stat"><b>32</b><span>${t('團員','Thành viên')}</span></div><div class="card stat"><b>5</b><span>${t('旅遊天數','Ngày')}</span></div><div class="card stat"><b>2</b><span>${t('住宿飯店','Khách sạn')}</span></div></div><div class="section-head"><h2>${t('快速入口','Lối tắt')}</h2><span>Quick Access</span></div><div class="grid quick-grid">${[['checkin','✅','每日簽到','Điểm danh hằng ngày'],['notifications','🔔','即時通知中心','Trung tâm thông báo'],['map','🗺️','GPS 地圖模式','Bản đồ GPS'],['guide','📖','電子旅行手冊','Cẩm nang số'],['itinerary','🗓️','五日行程','Lịch trình'],['resort','🌺','大紅花攻略','Lexis Guide'],['budget','💰','每日費用','Chi phí'],['food','🍜','美食清單','Ẩm thực'],['shopping','🛍️','伴手禮','Quà tặng'],['rooms','🏨','房間分配','Phòng']].map(x=>`<a class="card quick" href="#/${x[0]}" style="text-decoration:none"><i>${x[1]}</i><b>${t(x[2],x[3])}</b><small>Tap to open</small></a>`).join('')}</div><div class="section-head"><h2>${t('機場接送','Đưa đón sân bay')}</h2><span>Airport Transfer</span></div><div class="grid transfer-grid">${[AIRPORT_TRANSFER.outbound,AIRPORT_TRANSFER.return].map(x=>`<article class="card transfer-card"><div class="transfer-title"><b>${x.date.slice(5)} · ${t(x.typeZh,x.typeVi)}</b><span class="badge included">${x.flight}</span></div><div class="transfer-times"><div><small>${t('集合','Tập trung')}</small><strong>${x.meetingTime}</strong></div><div><small>${t('發車','Khởi hành')}</small><strong>${x.departureTime}</strong></div><div><small>${t('班機','Chuyến bay')}</small><strong>${x.flightTime}</strong></div></div><p>📍 ${t(x.fromZh,x.fromVi)}<br>→ ${t(x.toZh,x.toVi)}</p><small>${t(x.noteZh,x.noteVi)}</small></article>`).join('')}</div><div class="section-head"><h2>${t('重要提醒','Lưu ý')}</h2></div><div class="notice">🎁 ${t('大紅花 SKY BAR 每人一杯無酒精飲料已含於團費。源昌隆下午茶（海南茶、咖椰吐司、生熟蛋）亦已包含。','Mỗi người được một ly nước không cồn tại SKY BAR. Trà chiều Kafei Dian cũng đã bao gồm.')}</div>`, 'home')}
function itinerary(){const d=ITINERARY.find(x=>x.day===state.day)||ITINERARY[0];return shell(`<div class="section-head"><h2>${t('五日正式行程','Lịch trình chính thức')}</h2><span>Milestone 2-3 Final</span></div><div class="day-tabs">${ITINERARY.map(x=>`<button class="day-tab ${x.day===state.day?'active':''}" data-day="${x.day}">DAY ${x.day}<br>${x.date.slice(5)}</button>`).join('')}</div><div class="card day-card"><div class="day-cover"><p>DAY ${d.day} · ${d.date}</p><h2>${t(d.titleZh,d.titleVi)}</h2><p>🏨 ${d.hotel}</p></div><div class="event-list">${d.items.map(i=>`<div class="event"><div class="time">${esc(i.time)}</div><div class="dot"></div><div><b>${t(i.zh,i.vi)}${i.included?`<span class="badge included">🎁 ${t('已含','Đã gồm')}</span>`:''}${i.optional?`<span class="badge optional">✨ ${t('自費','Tự chọn')}</span>`:''}</b></div></div>`).join('')}</div></div><div class="meal-hotel"><div class="card info-card"><h3>🍽️ ${t('當日餐食','Bữa ăn')}</h3><ul>${d.meals.map(m=>`<li>${m}</li>`).join('')}</ul></div></div>`, 'itinerary')}
function budget(){return shell(`<div class="section-head"><h2>${t('每日費用資訊卡','Thẻ chi phí hàng ngày')}</h2><span>Milestone 2-4</span></div><div class="notice">💡 ${t('建議攜帶現金 RM150–500，購物費用另計。以下為參考區間，實際以現場公告為準。','Nên mang RM150–500 tiền mặt, chưa bao gồm mua sắm. Giá chỉ tham khảo.')}</div><div class="grid" style="margin-top:11px">${DAILY_BUDGET.map(x=>`<div class="card budget-card"><div class="budget-top"><b>DAY ${x.day}</b><span class="badge optional">RM</span></div><div class="budget-values"><div class="budget-value"><span>${t('基本支出','Chi phí cơ bản')}</span><b>${x.basic}</b></div><div class="budget-value"><span>${t('自費／購物','Tự chọn / mua sắm')}</span><b>${x.optional}</b></div></div><p>${x.note}</p></div>`).join('')}</div>`, 'budget')}
function products(title,subtitle,data,active){return shell(`<div class="section-head"><h2>${title}</h2><span>${subtitle}</span></div><div class="grid product-grid">${data.map(x=>`<div class="card product"><i>${x.icon}</i><b>${t(x.nameZh||x.zh,x.nameVi||x.vi)}</b><span>${x.price}</span><small>${x.place||x.where||x.note||''}</small></div>`).join('')}</div>`,active)}
function food(){return products(t('馬來西亞美食清單','Danh sách ẩm thực'),'Food Guide',FOODS,'food')}
function shopping(){return products(t('必買伴手禮','Quà tặng nên mua'),'Shopping Guide',SHOPPING,'shopping')}
function resort(){return shell(`<div class="section-head"><h2>${t('大紅花自費活動','Hoạt động tự chọn Lexis')}</h2><span>Resort Guide</span></div><div class="notice">⚠️ ${t('價格僅供參考，依飯店現場公告為準。水上活動可能因天候調整或取消。','Giá chỉ tham khảo. Hoạt động trên biển có thể thay đổi do thời tiết.')}</div>${[['water','🚤','水上休閒','Trên biển'],['land','🚲','陸上休閒','Trên đất liền'],['indoor','💆','館內與餐飲','Trong khách sạn']].map(g=>`<div class="section-head"><h2>${g[1]} ${t(g[2],g[3])}</h2></div><div class="grid activity-grid">${RESORT_ACTIVITIES.filter(x=>x.group===g[0]).map(x=>`<div class="card activity"><i>${x.icon}</i><b>${t(x.zh,x.vi)}</b><span>${x.price}</span><small>${x.note}</small></div>`).join('')}</div>`).join('')}`, 'resort')}

function guideText(value){return t(value?.zh||value?.titleZh||'',value?.vi||value?.titleVi||'')}
function guideCard(card){const lines=state.lang==='zh'?(card.linesZh||[]):(card.linesVi||[]);return `<article class="card guide-detail-card"><div class="guide-card-title"><i>${card.icon||'•'}</i><h3>${t(card.titleZh,card.titleVi)}</h3></div><ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${card.link?`<a class="guide-official-link" href="${card.link}" target="_blank" rel="noopener">↗ ${t(card.linkLabelZh,card.linkLabelVi)}</a>`:''}</article>`}
function guideCategoryView(id){const cat=DIGITAL_GUIDE.categories.find(x=>x.id===id);const section=DIGITAL_GUIDE.sections[id];if(!cat||!section)return '';
  let body='';
  if(section.cards)body=`<div class="grid guide-detail-grid">${section.cards.map(guideCard).join('')}</div>`;
  if(section.phrases)body=`<div class="phrase-list">${section.phrases.map(p=>`<button class="card phrase-card" type="button" data-speak="${esc(state.lang==='zh'?p.zh:p.vi)}"><strong>${esc(state.lang==='zh'?p.zh:p.vi)}</strong><span>${esc(state.lang==='zh'?p.vi:p.zh)}</span><small>MY: ${esc(p.ms)} · EN: ${esc(p.en)}</small></button>`).join('')}</div>`;
  if(section.checks)body=`<div class="card guide-checklist">${section.checks.map(c=>{const checked=localStorage.getItem('guide-check-'+c.id)==='1';return `<label class="guide-check"><input type="checkbox" data-guide-check="${c.id}" ${checked?'checked':''}><span>${esc(t(c.zh,c.vi))}</span></label>`}).join('')}<button class="guide-reset" id="guideReset" type="button">${t('清除全部勾選','Xóa tất cả dấu chọn')}</button></div>`;
  return `<button class="guide-back" id="guideBack" type="button">‹ ${t('返回手冊目錄','Trở lại mục lục')}</button><section class="guide-category-hero"><div>${cat.icon}</div><h1>${t(cat.titleZh,cat.titleVi)}</h1><p>${t(section.heroZh,section.heroVi)}</p></section>${body}`
}
function guide(){
  if(state.guideCategory)return shell(`<div class="guide-page">${guideCategoryView(state.guideCategory)}</div>`,'guide');
  const q=state.guideQuery.trim().toLowerCase();
  const cats=DIGITAL_GUIDE.categories.filter(c=>`${c.titleZh} ${c.titleVi} ${c.summaryZh} ${c.summaryVi}`.toLowerCase().includes(q));
  return shell(`<section class="guide-main-hero"><span class="pill">Milestone 3-1 · Release v3.0</span><h1>${t('電子旅行手冊','Cẩm nang du lịch số')}</h1><p>${t('出發、入境、飯店、付款、文化與緊急資訊，一頁快速查找。','Tra cứu nhanh thông tin khởi hành, nhập cảnh, khách sạn, thanh toán, văn hóa và khẩn cấp.')}</p></section><input class="search guide-search" id="guideSearch" value="${esc(state.guideQuery)}" placeholder="${t('搜尋：護照、插座、緊急電話…','Tìm: hộ chiếu, ổ cắm, khẩn cấp…')}"><div class="notice guide-disclaimer">⚠️ ${t(DIGITAL_GUIDE.meta.disclaimerZh,DIGITAL_GUIDE.meta.disclaimerVi)}</div><div class="grid guide-grid">${cats.map(c=>`<button class="card guide-category" type="button" data-guide-category="${c.id}"><i>${c.icon}</i><span><b>${t(c.titleZh,c.titleVi)}</b><small>${t(c.summaryZh,c.summaryVi)}</small></span><em>›</em></button>`).join('')||`<div class="empty">${t('找不到相關內容','Không tìm thấy nội dung')}</div>`}</div><div class="section-head"><h2>${t('後續智慧模組','Mô-đun thông minh tiếp theo')}</h2><span>Roadmap</span></div><div class="grid future-grid">${DIGITAL_GUIDE.futureModules.map(x=>`<div class="card future-card"><i>${x.icon}</i><b>${t(x.titleZh,x.titleVi)}</b><small>${x.status}</small></div>`).join('')}</div>`,'guide')
}


function mapFilteredLocations(){
  const q=state.mapQuery.trim().toLowerCase();
  return MAP_LOCATIONS.filter(x=>(state.mapCategory==='all'||x.category===state.mapCategory)&&(!state.mapDay||x.day===state.mapDay)&&`${x.nameZh} ${x.nameVi} ${x.addressZh} ${x.addressVi} ${x.noteZh} ${x.noteVi}`.toLowerCase().includes(q));
}
function haversine(a,b){const R=6371,toRad=n=>n*Math.PI/180;const dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);const q=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function googleNavUrl(x){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(x.query||`${x.lat},${x.lng}`)}`}
function mapLocationCards(list){return list.map(x=>{const distance=state.userPosition?haversine(state.userPosition,x).toFixed(1):'';return `<article class="card map-location-card" data-map-focus="${x.id}"><div class="map-location-icon">${x.icon}</div><div class="map-location-body"><div class="map-location-title"><b>${t(x.nameZh,x.nameVi)}</b><span>DAY ${x.day}</span></div><small>📍 ${t(x.addressZh,x.addressVi)}</small><p>${t(x.noteZh,x.noteVi)}</p>${distance?`<em>距離約 ${distance} km</em>`:''}</div><a class="map-nav-btn" href="${googleNavUrl(x)}" target="_blank" rel="noopener" aria-label="導航">➤</a></article>`}).join('')||`<div class="empty">${t('找不到符合的地點','Không tìm thấy địa điểm phù hợp')}</div>`}
function mapPage(){const list=mapFilteredLocations();return shell(`<section class="map-hero"><span class="pill">Milestone 3-2 · GPS Map</span><h1>${t('GPS 地圖模式','Chế độ bản đồ GPS')}</h1><p>${t('依照每日行程查看飯店、景點、美食與購物地點，並可一鍵開啟 Google Maps 導航。','Xem khách sạn, điểm tham quan, ẩm thực và mua sắm theo từng ngày, mở Google Maps chỉ với một chạm.')}</p></section><div class="map-toolbar"><input class="search" id="mapSearch" value="${esc(state.mapQuery)}" placeholder="${t('搜尋地點、景點或美食','Tìm địa điểm, điểm tham quan hoặc ẩm thực')}"><button class="locate-btn" id="locateMe" type="button">◎ ${t('我的位置','Vị trí của tôi')}</button></div><div class="map-filter-row">${MAP_CATEGORIES.map(c=>`<button class="map-filter ${state.mapCategory===c.id?'active':''}" data-map-category="${c.id}">${c.icon} ${t(c.zh,c.vi)}</button>`).join('')}</div><div class="day-tabs map-day-tabs"><button class="day-tab ${state.mapDay===0?'active':''}" data-map-day="0">${t('全部天數','Tất cả ngày')}</button>${[1,2,3,4,5].map(d=>`<button class="day-tab ${state.mapDay===d?'active':''}" data-map-day="${d}">DAY ${d}</button>`).join('')}</div><div class="map-status" id="mapStatus">${t('地圖需要網路連線；離線時仍可查看下方地點清單。','Bản đồ cần internet; khi ngoại tuyến vẫn xem được danh sách địa điểm bên dưới.')}</div><div id="gpsMap" class="gps-map" aria-label="GPS map"></div><div class="section-head"><h2>${t('地點清單','Danh sách địa điểm')}</h2><span>${list.length} places</span></div><div id="mapLocationList" class="map-location-list">${mapLocationCards(list)}</div>`, 'map')}
function initMap(){
  const el=document.getElementById('gpsMap'); if(!el)return;
  if(!window.L){el.innerHTML=`<div class="map-offline">${t('目前無法載入互動地圖，請確認網路連線。','Không thể tải bản đồ tương tác. Vui lòng kiểm tra kết nối mạng.')}</div>`;return;}
  const list=mapFilteredLocations();
  state.mapInstance=L.map(el,{zoomControl:true}).setView([3.14,101.70],9);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(state.mapInstance);
  state.mapMarkers=list.map(x=>{const icon=L.divIcon({className:'map-div-icon',html:`<div>${x.icon}</div>`,iconSize:[34,34],iconAnchor:[17,17]});const m=L.marker([x.lat,x.lng],{icon}).addTo(state.mapInstance).bindPopup(`<div class="map-popup"><b>${esc(t(x.nameZh,x.nameVi))}</b><small>${esc(t(x.addressZh,x.addressVi))}</small><a href="${googleNavUrl(x)}" target="_blank" rel="noopener">${t('開始導航','Bắt đầu chỉ đường')}</a></div>`);m._locationId=x.id;return m});
  if(list.length){const group=L.featureGroup(state.mapMarkers);state.mapInstance.fitBounds(group.getBounds().pad(.12),{maxZoom:13})}
  if(state.userPosition){L.circleMarker([state.userPosition.lat,state.userPosition.lng],{radius:9,weight:3,color:'#167d72',fillColor:'#fff',fillOpacity:1}).addTo(state.mapInstance).bindPopup(t('我的位置','Vị trí của tôi'))}
  setTimeout(()=>state.mapInstance?.invalidateSize(),100);
}
function refreshMap(){state.mapInstance?.remove();state.mapInstance=null;render()}


function storedAnnouncements(){try{return JSON.parse(localStorage.getItem('mtc-custom-announcements')||'[]')}catch{return []}}
function allAnnouncements(){return [...storedAnnouncements(),...ANNOUNCEMENTS].sort((a,b)=>`${b.date||''} ${b.time||''}`.localeCompare(`${a.date||''} ${a.time||''}`))}
function readNoticeIds(){try{return new Set(JSON.parse(localStorage.getItem('mtc-read-announcements')||'[]'))}catch{return new Set()}}
function setNoticeRead(id){const ids=readNoticeIds();ids.add(id);localStorage.setItem('mtc-read-announcements',JSON.stringify([...ids]))}
function noticeType(x){return ANNOUNCEMENT_TYPES.find(y=>y.id===x.type)||ANNOUNCEMENT_TYPES[0]}
function noticeCards(list){const read=readNoticeIds();return list.map(x=>{const type=noticeType(x);return `<article class="card notice-card ${read.has(x.id)?'read':''} ${x.priority==='urgent'?'urgent':''}" data-notice-id="${esc(x.id)}"><div class="notice-icon">${type.icon}</div><div class="notice-body"><div class="notice-title-row"><b>${esc(t(x.titleZh,x.titleVi))}</b><span>${esc(t(type.zh,type.vi))}</span></div><p>${esc(t(x.messageZh,x.messageVi))}</p><small>${esc(x.date||'')} ${esc(x.time||'')} ${x.locationZh?`· 📍 ${esc(t(x.locationZh,x.locationVi))}`:''}</small></div><button class="notice-read-btn" type="button" aria-label="mark read">${read.has(x.id)?'✓':'●'}</button></article>`}).join('')||`<div class="empty">${t('目前沒有通知','Hiện không có thông báo')}</div>`}
function notificationsPage(){const all=allAnnouncements();const list=state.noticeFilter==='all'?all:all.filter(x=>x.type===state.noticeFilter);const unread=all.filter(x=>!readNoticeIds().has(x.id)).length;return shell(`<section class="notification-hero"><span class="pill">Milestone 3-3 · Notification Center</span><h1>${t('即時通知中心','Trung tâm thông báo')}</h1><p>${t('集中查看集合時間、巴士位置、房務與臨時公告。通知會保存在此裝置。','Xem giờ tập trung, vị trí xe, thông tin phòng và thông báo khẩn. Thông báo được lưu trên thiết bị này.')}</p><div class="notification-summary"><b>${unread}</b><span>${t('則未讀通知','thông báo chưa đọc')}</span></div></section><div class="notification-actions"><button id="enableBrowserNotice" type="button">🔔 ${t('開啟瀏覽器通知','Bật thông báo trình duyệt')}</button><button id="toggleNoticeEditor" type="button">✚ ${t('領隊新增公告','Trưởng đoàn thêm thông báo')}</button></div><div class="notice-limit">${t('目前為裝置端通知中心；未連接雲端後台時，新增公告只會保存在此手機／電腦，無法自動同步到其他團員裝置。','Hiện đây là trung tâm thông báo trên thiết bị. Khi chưa kết nối máy chủ đám mây, thông báo mới chỉ lưu trên điện thoại/máy tính này và không tự đồng bộ sang thiết bị khác.')}</div>${state.noticeEditor?noticeEditor():''}<div class="map-filter-row">${ANNOUNCEMENT_TYPES.map(c=>`<button class="map-filter ${state.noticeFilter===c.id?'active':''}" data-notice-filter="${c.id}">${c.icon} ${t(c.zh,c.vi)}</button>`).join('')}</div><div class="notification-list">${noticeCards(list)}</div>`, 'notifications')}
function noticeEditor(){return `<form class="card notice-editor" id="noticeEditor"><h3>${t('新增公告','Thêm thông báo')}</h3><div class="notice-form-grid"><label>${t('類型','Loại')}<select name="type">${ANNOUNCEMENT_TYPES.filter(x=>x.id!=='all').map(x=>`<option value="${x.id}">${x.icon} ${t(x.zh,x.vi)}</option>`).join('')}</select></label><label>${t('優先層級','Mức ưu tiên')}<select name="priority"><option value="normal">${t('一般','Thường')}</option><option value="urgent">${t('緊急','Khẩn cấp')}</option></select></label><label>${t('日期','Ngày')}<input name="date" type="date" required></label><label>${t('時間','Giờ')}<input name="time" type="time"></label></div><label>${t('中文標題','Tiêu đề tiếng Hoa')}<input name="titleZh" required placeholder="例如：10:10 大廳集合"></label><label>${t('越南文標題','Tiêu đề tiếng Việt')}<input name="titleVi" required placeholder="Ví dụ: Tập trung tại sảnh lúc 10:10"></label><label>${t('中文內容','Nội dung tiếng Hoa')}<textarea name="messageZh" required></textarea></label><label>${t('越南文內容','Nội dung tiếng Việt')}<textarea name="messageVi" required></textarea></label><div class="notice-form-grid"><label>${t('中文地點','Địa điểm tiếng Hoa')}<input name="locationZh"></label><label>${t('越南文地點','Địa điểm tiếng Việt')}<input name="locationVi"></label></div><button class="notice-save" type="submit">${t('儲存公告','Lưu thông báo')}</button></form>`}
function showBrowserNotification(x){if(!('Notification' in window)||Notification.permission!=='granted')return;const n=new Notification(t(x.titleZh,x.titleVi),{body:t(x.messageZh,x.messageVi),icon:'./icons/icon-192.png',tag:x.id});n.onclick=()=>{window.focus();location.hash='#/notifications'}}


function checkinKey(day,memberId){return `mtc-checkin-d${day}-m${memberId}`}
function checkinValue(day,memberId){return localStorage.getItem(checkinKey(day,memberId))||'pending'}
function setCheckinValue(day,memberId,status){localStorage.setItem(checkinKey(day,memberId),status)}
function checkinCounts(day){const out={present:0,late:0,absent:0,pending:0};MEMBERS.forEach(m=>out[checkinValue(day,m.id)]++);return out}
function checkinMemberCards(list){return list.map(m=>{const st=checkinValue(state.checkinDay,m.id);const def=CHECKIN_STATUS.find(x=>x.id===st)||CHECKIN_STATUS[3];return `<article class="card checkin-member ${st}"><div class="checkin-person"><div class="avatar">${m.number===32?'🧑‍✈️':'👤'}</div><div><b>${esc(m.nameZh)}</b><small>${esc(m.nameEn)}</small></div></div><div class="checkin-status-current">${def.icon} ${t(def.zh,def.vi)}</div><div class="checkin-buttons">${CHECKIN_STATUS.filter(x=>x.id!=='pending').map(x=>`<button type="button" class="${st===x.id?'active':''}" data-checkin-member="${m.id}" data-checkin-status="${x.id}">${x.icon}<span>${t(x.zh,x.vi)}</span></button>`).join('')}</div></article>`}).join('')||`<div class="empty">${t('找不到團員','Không tìm thấy thành viên')}</div>`}
function checkinPage(){const day=CHECKIN_DAYS.find(x=>x.day===state.checkinDay)||CHECKIN_DAYS[0];const q=state.checkinQuery.trim().toLowerCase();let list=MEMBERS.filter(m=>`${m.nameZh} ${m.nameEn}`.toLowerCase().includes(q));if(state.checkinFilter!=='all')list=list.filter(m=>checkinValue(state.checkinDay,m.id)===state.checkinFilter);const c=checkinCounts(state.checkinDay);return shell(`<section class="checkin-hero"><span class="pill">Milestone 3-4 · Daily Check-in</span><h1>${t('每日簽到','Điểm danh hằng ngày')}</h1><p>${t('依每日集合狀況記錄已到、遲到或缺席；資料保存在目前裝置。','Ghi nhận có mặt, đến trễ hoặc vắng mặt mỗi ngày; dữ liệu được lưu trên thiết bị này.')}</p></section><div class="day-tabs checkin-days">${CHECKIN_DAYS.map(x=>`<button class="day-tab ${x.day===state.checkinDay?'active':''}" data-checkin-day="${x.day}">DAY ${x.day}<br>${x.date.slice(5)}</button>`).join('')}</div><div class="card checkin-session"><div><small>${t('今日簽到主題','Chủ đề điểm danh')}</small><h3>${t(day.titleZh,day.titleVi)}</h3><p>📍 ${t(day.locationZh,day.locationVi)}</p></div><button id="markAllPresent" type="button">✓ ${t('全部已到','Tất cả có mặt')}</button></div><div class="checkin-summary"><div><b>${c.present}</b><span>✅ ${t('已到','Có mặt')}</span></div><div><b>${c.late}</b><span>⏰ ${t('遲到','Đến trễ')}</span></div><div><b>${c.absent}</b><span>❌ ${t('缺席','Vắng')}</span></div><div><b>${c.pending}</b><span>● ${t('未簽到','Chưa điểm danh')}</span></div></div><div class="checkin-toolbar"><input class="search" id="checkinSearch" value="${esc(state.checkinQuery)}" placeholder="${t('搜尋團員姓名','Tìm tên thành viên')}"><button id="resetCheckin" type="button">↺ ${t('重設本日','Đặt lại ngày này')}</button></div><div class="map-filter-row">${[['all','👥','全部','Tất cả'],...CHECKIN_STATUS.map(x=>[x.id,x.icon,x.zh,x.vi])].map(x=>`<button class="map-filter ${state.checkinFilter===x[0]?'active':''}" data-checkin-filter="${x[0]}">${x[1]} ${t(x[2],x[3])}</button>`).join('')}</div><div class="checkin-list">${checkinMemberCards(list)}</div><div class="notice-limit">${t('目前為單機版簽到；未連接雲端後台時，簽到結果只保存在此手機／電腦，不會同步到其他裝置。','Hiện là điểm danh trên một thiết bị. Khi chưa kết nối máy chủ đám mây, kết quả chỉ lưu trên điện thoại/máy tính này và không đồng bộ sang thiết bị khác.')}</div>`, 'checkin')}

function traveler(){return shell(`<div class="section-head"><h2>${t('團員與機位','Thành viên và chỗ ngồi')}</h2><span>${MEMBERS.length} people</span></div><input class="search" id="memberSearch" placeholder="${t('搜尋中文／英文姓名','Tìm tên tiếng Hoa / Anh')}"><div id="memberList" class="grid" style="margin-top:11px">${memberCards(MEMBERS)}</div>`, 'traveler')}
function memberCards(list){return list.map(m=>`<div class="card person"><div class="person-head"><div class="avatar">${m.number===32?'🧑‍✈️':'👤'}</div><div><h3>${esc(m.nameZh)} ${m.number===32?'<span class="badge included">領隊</span>':''}</h3><small>${esc(m.nameEn)}</small></div></div><div class="person-meta"><div class="meta"><span>JX725</span><b>${m.seatOutbound}</b></div><div class="meta"><span>JX726</span><b>${m.seatReturn}</b></div><div class="meta"><span>${t('機場交通','Di chuyển')}</span><b>${esc(m.airportTransport)}</b></div></div></div>`).join('')||`<div class="empty">${t('找不到團員','Không tìm thấy')}</div>`}
function rooms(){const groups=['lexis','sunway'];return shell(`<div class="section-head"><h2>${t('房間分配','Phân phòng')}</h2><span>${t('分房代碼非正式房號','Mã phòng không phải số phòng thật')}</span></div><div class="day-tabs">${groups.map(h=>`<button class="day-tab ${state.hotel===h?'active':''}" data-hotel="${h}">${h==='lexis'?'🌺 Lexis Hibiscus':'🏙️ Sunway Velocity'}</button>`).join('')}</div><div class="grid">${ROOMS.filter(r=>r.hotelId===state.hotel).map(r=>`<div class="card room-card"><h3>${r.assignmentCode} · ${t(r.roomTypeZh,r.roomTypeVi)}</h3><p>${r.memberIds.map(id=>MEMBERS.find(m=>m.id===id)?.nameZh).filter(Boolean).join('、')}</p></div>`).join('')}</div>`, 'rooms')}
function render(){const r=route();const map={home,itinerary,budget,food,shopping,resort,traveler,rooms,guide,map:mapPage,notifications:notificationsPage,checkin:checkinPage};document.getElementById('app').innerHTML=map[r]();bind(r)}
function bind(r){
  document.getElementById('langBtn')?.addEventListener('click',()=>{state.lang=state.lang==='zh'?'vi':'zh';localStorage.setItem('mtc-lang',state.lang);render()});
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.day);render()});
  document.querySelectorAll('[data-hotel]').forEach(b=>b.onclick=()=>{state.hotel=b.dataset.hotel;render()});
  if(r==='traveler'){document.getElementById('memberSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.getElementById('memberList').innerHTML=memberCards(MEMBERS.filter(m=>`${m.nameZh} ${m.nameEn}`.toLowerCase().includes(q)))})}
  if(r==='map'){
    initMap();
    document.getElementById('mapSearch')?.addEventListener('input',e=>{state.mapQuery=e.target.value;refreshMap()});
    document.querySelectorAll('[data-map-category]').forEach(b=>b.onclick=()=>{state.mapCategory=b.dataset.mapCategory;refreshMap()});
    document.querySelectorAll('[data-map-day]').forEach(b=>b.onclick=()=>{state.mapDay=Number(b.dataset.mapDay);refreshMap()});
    document.getElementById('locateMe')?.addEventListener('click',()=>{
      const status=document.getElementById('mapStatus');
      if(!navigator.geolocation){if(status)status.textContent=t('此裝置不支援定位功能。','Thiết bị này không hỗ trợ định vị.');return}
      if(status)status.textContent=t('正在取得目前位置…','Đang lấy vị trí hiện tại…');
      navigator.geolocation.getCurrentPosition(pos=>{state.userPosition={lat:pos.coords.latitude,lng:pos.coords.longitude};refreshMap()},()=>{if(status)status.textContent=t('無法取得位置，請確認已允許定位權限。','Không thể lấy vị trí. Vui lòng cho phép quyền định vị.')},{enableHighAccuracy:true,timeout:12000,maximumAge:60000});
    });
    document.querySelectorAll('[data-map-focus]').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('a'))return;const marker=state.mapMarkers.find(m=>m._locationId===card.dataset.mapFocus);if(marker&&state.mapInstance){state.mapInstance.setView(marker.getLatLng(),15);marker.openPopup();document.getElementById('gpsMap')?.scrollIntoView({behavior:'smooth',block:'center'})}}));
  }
  if(r==='checkin'){
    document.querySelectorAll('[data-checkin-day]').forEach(b=>b.onclick=()=>{state.checkinDay=Number(b.dataset.checkinDay);render()});
    document.querySelectorAll('[data-checkin-filter]').forEach(b=>b.onclick=()=>{state.checkinFilter=b.dataset.checkinFilter;render()});
    document.getElementById('checkinSearch')?.addEventListener('input',e=>{state.checkinQuery=e.target.value;render()});
    document.querySelectorAll('[data-checkin-member]').forEach(b=>b.onclick=()=>{setCheckinValue(state.checkinDay,Number(b.dataset.checkinMember),b.dataset.checkinStatus);render()});
    document.getElementById('markAllPresent')?.addEventListener('click',()=>{MEMBERS.forEach(m=>setCheckinValue(state.checkinDay,m.id,'present'));render()});
    document.getElementById('resetCheckin')?.addEventListener('click',()=>{if(confirm(t('確定要清除本日所有簽到紀錄？','Bạn có chắc muốn xóa toàn bộ điểm danh hôm nay?'))){MEMBERS.forEach(m=>localStorage.removeItem(checkinKey(state.checkinDay,m.id)));render()}});
  }
  if(r==='notifications'){
    document.querySelectorAll('[data-notice-filter]').forEach(b=>b.onclick=()=>{state.noticeFilter=b.dataset.noticeFilter;render()});
    document.getElementById('toggleNoticeEditor')?.addEventListener('click',()=>{state.noticeEditor=!state.noticeEditor;render()});
    document.getElementById('enableBrowserNotice')?.addEventListener('click',async()=>{if(!('Notification' in window)){alert(t('此瀏覽器不支援通知功能。','Trình duyệt này không hỗ trợ thông báo.'));return}const p=await Notification.requestPermission();alert(p==='granted'?t('瀏覽器通知已開啟。','Đã bật thông báo trình duyệt.'):t('未取得通知權限。','Chưa được cấp quyền thông báo.'))});
    document.querySelectorAll('[data-notice-id]').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('button'))return;setNoticeRead(c.dataset.noticeId);render()}));
    document.querySelectorAll('.notice-read-btn').forEach(b=>b.onclick=e=>{const card=e.currentTarget.closest('[data-notice-id]');setNoticeRead(card.dataset.noticeId);render()});
    document.getElementById('noticeEditor')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),x={id:'local-'+Date.now(),type:f.get('type'),priority:f.get('priority'),date:f.get('date'),time:f.get('time'),titleZh:f.get('titleZh'),titleVi:f.get('titleVi'),messageZh:f.get('messageZh'),messageVi:f.get('messageVi'),locationZh:f.get('locationZh'),locationVi:f.get('locationVi')};const saved=storedAnnouncements();saved.unshift(x);localStorage.setItem('mtc-custom-announcements',JSON.stringify(saved));state.noticeEditor=false;showBrowserNotification(x);render()});
  }
  if(r==='guide'){
    document.getElementById('guideSearch')?.addEventListener('input',e=>{state.guideQuery=e.target.value;render()});
    document.querySelectorAll('[data-guide-category]').forEach(b=>b.onclick=()=>{state.guideCategory=b.dataset.guideCategory;render()});
    document.getElementById('guideBack')?.addEventListener('click',()=>{state.guideCategory=null;render()});
    document.querySelectorAll('[data-guide-check]').forEach(c=>c.onchange=()=>localStorage.setItem('guide-check-'+c.dataset.guideCheck,c.checked?'1':'0'));
    document.getElementById('guideReset')?.addEventListener('click',()=>{DIGITAL_GUIDE.sections.checklist.checks.forEach(c=>localStorage.removeItem('guide-check-'+c.id));render()});
    document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>{if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(b.dataset.speak);u.lang=state.lang==='zh'?'zh-TW':'vi-VN';speechSynthesis.speak(u)}});
  }
}
window.addEventListener('hashchange',render);render();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=340').catch(console.warn))}
