import { ITINERARY } from '../data/trip/itinerary.js';
import { DAILY_BUDGET } from '../data/trip/daily-budget.js';
import { FOODS } from '../data/trip/foods.js';
import { SHOPPING } from '../data/trip/shopping.js';
import { RESORT_ACTIVITIES } from '../data/trip/resort.js';
import { MEMBERS } from '../data/trip/members.js';
import { ROOMS } from '../data/trip/rooms.js';
import { VERSION } from '../data/system/version.js';
import { AIRPORT_TRANSFER } from '../data/trip/airport-transfer.js';
import { DIGITAL_GUIDE } from '../data/trip/guide.js';

const state={lang:localStorage.getItem('mtc-lang')||'zh',day:1,hotel:'lexis',guideCategory:null,guideQuery:''};
const t=(zh,vi)=>state.lang==='zh'?zh:vi;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const routes=['home','itinerary','budget','food','shopping','resort','traveler','rooms','guide'];
function route(){const r=(location.hash.replace('#/','')||'home').split('?')[0];return routes.includes(r)?r:'home'}
function header(){return `<div class="topbar"><div class="brand"><div class="brand-mark">🇲🇾</div><div><b>${t('馬來西亞手帳 2026','Sổ tay Malaysia 2026')}</b><small>國能員旅 · Release v3.0</small></div></div><button class="lang" id="langBtn">${state.lang==='zh'?'VI':'中'}</button></div>`}
function nav(active){const items=[['home','🏠',t('首頁','Trang chủ')],['itinerary','🗓️',t('行程','Lịch trình')],['budget','💰',t('費用','Chi phí')],['traveler','👥',t('團員','Thành viên')],['guide','📖',t('手冊','Cẩm nang')]];return `<nav class="nav"><div class="nav-inner">${items.map(([r,i,l])=>`<a href="#/${r}" class="${active===r?'active':''}"><i>${i}</i>${l}</a>`).join('')}</div></nav>`}
function shell(content,active){return `<div class="shell">${header()}<main>${content}<div class="version">Release ${VERSION.version} · ${VERSION.build}</div></main>${nav(active)}</div>`}
function home(){return shell(`<section class="hero"><span class="pill">✈️ 2026/09/20–09/24</span><h1>${t('馬來西亞五日員工旅遊','Du lịch Malaysia 5 ngày')}</h1><p>${t('行程、房間、機位、每日費用、美食與伴手禮一次整理。','Tổng hợp lịch trình, phòng, chỗ ngồi, chi phí, ẩm thực và quà tặng.')}</p></section><div class="grid stats" style="margin-top:12px"><div class="card stat"><b>32</b><span>${t('團員','Thành viên')}</span></div><div class="card stat"><b>5</b><span>${t('旅遊天數','Ngày')}</span></div><div class="card stat"><b>2</b><span>${t('住宿飯店','Khách sạn')}</span></div></div><div class="section-head"><h2>${t('快速入口','Lối tắt')}</h2><span>Quick Access</span></div><div class="grid quick-grid">${[['guide','📖','電子旅行手冊','Cẩm nang số'],['itinerary','🗓️','五日行程','Lịch trình'],['resort','🌺','大紅花攻略','Lexis Guide'],['budget','💰','每日費用','Chi phí'],['food','🍜','美食清單','Ẩm thực'],['shopping','🛍️','伴手禮','Quà tặng'],['rooms','🏨','房間分配','Phòng']].map(x=>`<a class="card quick" href="#/${x[0]}" style="text-decoration:none"><i>${x[1]}</i><b>${t(x[2],x[3])}</b><small>Tap to open</small></a>`).join('')}</div><div class="section-head"><h2>${t('機場接送','Đưa đón sân bay')}</h2><span>Airport Transfer</span></div><div class="grid transfer-grid">${[AIRPORT_TRANSFER.outbound,AIRPORT_TRANSFER.return].map(x=>`<article class="card transfer-card"><div class="transfer-title"><b>${x.date.slice(5)} · ${t(x.typeZh,x.typeVi)}</b><span class="badge included">${x.flight}</span></div><div class="transfer-times"><div><small>${t('集合','Tập trung')}</small><strong>${x.meetingTime}</strong></div><div><small>${t('發車','Khởi hành')}</small><strong>${x.departureTime}</strong></div><div><small>${t('班機','Chuyến bay')}</small><strong>${x.flightTime}</strong></div></div><p>📍 ${t(x.fromZh,x.fromVi)}<br>→ ${t(x.toZh,x.toVi)}</p><small>${t(x.noteZh,x.noteVi)}</small></article>`).join('')}</div><div class="section-head"><h2>${t('重要提醒','Lưu ý')}</h2></div><div class="notice">🎁 ${t('大紅花 SKY BAR 每人一杯無酒精飲料已含於團費。源昌隆下午茶（海南茶、咖椰吐司、生熟蛋）亦已包含。','Mỗi người được một ly nước không cồn tại SKY BAR. Trà chiều Kafei Dian cũng đã bao gồm.')}</div>`, 'home')}
function itinerary(){const d=ITINERARY.find(x=>x.day===state.day)||ITINERARY[0];return shell(`<div class="section-head"><h2>${t('五日正式行程','Lịch trình chính thức')}</h2><span>Milestone 2-3 Final</span></div><div class="day-tabs">${ITINERARY.map(x=>`<button class="day-tab ${x.day===state.day?'active':''}" data-day="${x.day}">DAY ${x.day}<br>${x.date.slice(5)}</button>`).join('')}</div><div class="card day-card"><div class="day-cover"><p>DAY ${d.day} · ${d.date}</p><h2>${t(d.titleZh,d.titleVi)}</h2><p>🏨 ${d.hotel}</p></div><div class="event-list">${d.items.map(i=>`<div class="event"><div class="time">${esc(i.time)}</div><div class="dot"></div><div><b>${t(i.zh,i.vi)}${i.included?`<span class="badge included">🎁 ${t('已含','Đã gồm')}</span>`:''}${i.optional?`<span class="badge optional">✨ ${t('自費','Tự chọn')}</span>`:''}</b></div></div>`).join('')}</div></div><div class="meal-hotel"><div class="card info-card"><h3>🍽️ ${t('當日餐食','Bữa ăn')}</h3><ul>${d.meals.map(m=>`<li>${m}</li>`).join('')}</ul></div></div>`, 'itinerary')}
function budget(){return shell(`<div class="section-head"><h2>${t('每日費用資訊卡','Thẻ chi phí hàng ngày')}</h2><span>Milestone 2-4</span></div><div class="notice">💡 ${t('建議攜帶現金 RM150–500，購物費用另計。以下為參考區間，實際以現場公告為準。','Nên mang RM150–500 tiền mặt, chưa bao gồm mua sắm. Giá chỉ tham khảo.')}</div><div class="grid" style="margin-top:11px">${DAILY_BUDGET.map(x=>`<div class="card budget-card"><div class="budget-top"><b>DAY ${x.day}</b><span class="badge optional">RM</span></div><div class="budget-values"><div class="budget-value"><span>${t('基本支出','Chi phí cơ bản')}</span><b>${x.basic}</b></div><div class="budget-value"><span>${t('自費／購物','Tự chọn / mua sắm')}</span><b>${x.optional}</b></div></div><p>${x.note}</p></div>`).join('')}</div>`, 'budget')}
function products(title,subtitle,data,active){return shell(`<div class="section-head"><h2>${title}</h2><span>${subtitle}</span></div><div class="grid product-grid">${data.map(x=>`<div class="card product"><i>${x.icon}</i><b>${t(x.nameZh||x.zh,x.nameVi||x.vi)}</b><span>${x.price}</span><small>${x.place||x.where||x.note||''}</small></div>`).join('')}</div>`,active)}
function food(){return products(t('馬來西亞美食清單','Danh sách ẩm thực'),'Food Guide',FOODS,'food')}
function shopping(){return products(t('必買伴手禮','Quà tặng nên mua'),'Shopping Guide',SHOPPING,'shopping')}
function resort(){return shell(`<div class="section-head"><h2>${t('大紅花自費活動','Hoạt động tự chọn Lexis')}</h2><span>Resort Guide</span></div><div class="notice">⚠️ ${t('價格僅供參考，依飯店現場公告為準。水上活動可能因天候調整或取消。','Giá chỉ tham khảo. Hoạt động trên biển có thể thay đổi do thời tiết.')}</div>${[['water','🚤','水上休閒','Trên biển'],['land','🚲','陸上休閒','Trên đất liền'],['indoor','💆','館內與餐飲','Trong khách sạn']].map(g=>`<div class="section-head"><h2>${g[1]} ${t(g[2],g[3])}</h2></div><div class="grid activity-grid">${RESORT_ACTIVITIES.filter(x=>x.group===g[0]).map(x=>`<div class="card activity"><i>${x.icon}</i><b>${t(x.zh,x.vi)}</b><span>${x.price}</span><small>${x.note}</small></div>`).join('')}</div>`).join('')}`, 'resort')}

function guideText(value){return t(value?.zh||value?.titleZh||'',value?.vi||value?.titleVi||'')}
function guideCard(card){const lines=state.lang==='zh'?(card.linesZh||[]):(card.linesVi||[]);return `<article class="card guide-detail-card"><div class="guide-card-title"><i>${card.icon||'•'}</i><h3>${t(card.titleZh,card.titleVi)}</h3></div><ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${card.link?`<a class="guide-official-link" href="${card.link}" target="_blank" rel="noopener">↗ ${t(card.linkLabelZh,card.linkLabelVi)}</a>`:''}</article>`}
function guideCategoryView(id){const cat=DIGITAL_GUIDE.categories.find(x=>x.id===id);const section=DIGITAL_GUIDE.sections[id];if(!cat||!section)return '';
  let body='';
  if(section.cards)body=`<div class="grid guide-detail-grid">${section.cards.map(guideCard).join('')}</div>`;
  if(section.phrases)body=`<div class="phrase-list">${section.phrases.map(p=>`<button class="card phrase-card" type="button" data-speak="${esc(state.lang==='zh'?p.zh:p.vi)}"><strong>${esc(state.lang==='zh'?p.zh:p.vi)}</strong><span>${esc(state.lang==='zh'?p.vi:p.zh)}</span><small>MY: ${esc(p.ms)} · EN: ${esc(p.en)}</small></button>`).join('')}</div>`;
  if(section.checks)body=`<div class="card guide-checklist">${section.checks.map(c=>{const checked=localStorage.getItem('guide-check-'+c.id)==='1';return `<label class="guide-check"><input type="checkbox" data-guide-check="${c.id}" ${checked?'checked':''}><span>${esc(t(c.zh,c.vi))}</span></label>`}).join('')}<button class="guide-reset" id="guideReset" type="button">${t('清除全部勾選','Xóa tất cả dấu chọn')}</button></div>`;
  return `<button class="guide-back" id="guideBack" type="button">‹ ${t('返回手冊目錄','Trở lại mục lục')}</button><section class="guide-category-hero"><div>${cat.icon}</div><h1>${t(cat.titleZh,cat.titleVi)}</h1><p>${t(section.heroZh,section.heroVi)}</p></section>${body}`
}
function guide(){
  if(state.guideCategory)return shell(`<div class="guide-page">${guideCategoryView(state.guideCategory)}</div>`,'guide');
  const q=state.guideQuery.trim().toLowerCase();
  const cats=DIGITAL_GUIDE.categories.filter(c=>`${c.titleZh} ${c.titleVi} ${c.summaryZh} ${c.summaryVi}`.toLowerCase().includes(q));
  return shell(`<section class="guide-main-hero"><span class="pill">Milestone 3-1 · Release v3.0</span><h1>${t('電子旅行手冊','Cẩm nang du lịch số')}</h1><p>${t('出發、入境、飯店、付款、文化與緊急資訊，一頁快速查找。','Tra cứu nhanh thông tin khởi hành, nhập cảnh, khách sạn, thanh toán, văn hóa và khẩn cấp.')}</p></section><input class="search guide-search" id="guideSearch" value="${esc(state.guideQuery)}" placeholder="${t('搜尋：護照、插座、緊急電話…','Tìm: hộ chiếu, ổ cắm, khẩn cấp…')}"><div class="notice guide-disclaimer">⚠️ ${t(DIGITAL_GUIDE.meta.disclaimerZh,DIGITAL_GUIDE.meta.disclaimerVi)}</div><div class="grid guide-grid">${cats.map(c=>`<button class="card guide-category" type="button" data-guide-category="${c.id}"><i>${c.icon}</i><span><b>${t(c.titleZh,c.titleVi)}</b><small>${t(c.summaryZh,c.summaryVi)}</small></span><em>›</em></button>`).join('')||`<div class="empty">${t('找不到相關內容','Không tìm thấy nội dung')}</div>`}</div><div class="section-head"><h2>${t('後續智慧模組','Mô-đun thông minh tiếp theo')}</h2><span>Roadmap</span></div><div class="grid future-grid">${DIGITAL_GUIDE.futureModules.map(x=>`<div class="card future-card"><i>${x.icon}</i><b>${t(x.titleZh,x.titleVi)}</b><small>${x.status}</small></div>`).join('')}</div>`,'guide')
}

function traveler(){return shell(`<div class="section-head"><h2>${t('團員與機位','Thành viên và chỗ ngồi')}</h2><span>${MEMBERS.length} people</span></div><input class="search" id="memberSearch" placeholder="${t('搜尋中文／英文姓名','Tìm tên tiếng Hoa / Anh')}"><div id="memberList" class="grid" style="margin-top:11px">${memberCards(MEMBERS)}</div>`, 'traveler')}
function memberCards(list){return list.map(m=>`<div class="card person"><div class="person-head"><div class="avatar">${m.number===32?'🧑‍✈️':'👤'}</div><div><h3>${esc(m.nameZh)} ${m.number===32?'<span class="badge included">領隊</span>':''}</h3><small>${esc(m.nameEn)}</small></div></div><div class="person-meta"><div class="meta"><span>JX725</span><b>${m.seatOutbound}</b></div><div class="meta"><span>JX726</span><b>${m.seatReturn}</b></div><div class="meta"><span>${t('機場交通','Di chuyển')}</span><b>${esc(m.airportTransport)}</b></div></div></div>`).join('')||`<div class="empty">${t('找不到團員','Không tìm thấy')}</div>`}
function rooms(){const groups=['lexis','sunway'];return shell(`<div class="section-head"><h2>${t('房間分配','Phân phòng')}</h2><span>${t('分房代碼非正式房號','Mã phòng không phải số phòng thật')}</span></div><div class="day-tabs">${groups.map(h=>`<button class="day-tab ${state.hotel===h?'active':''}" data-hotel="${h}">${h==='lexis'?'🌺 Lexis Hibiscus':'🏙️ Sunway Velocity'}</button>`).join('')}</div><div class="grid">${ROOMS.filter(r=>r.hotelId===state.hotel).map(r=>`<div class="card room-card"><h3>${r.assignmentCode} · ${t(r.roomTypeZh,r.roomTypeVi)}</h3><p>${r.memberIds.map(id=>MEMBERS.find(m=>m.id===id)?.nameZh).filter(Boolean).join('、')}</p></div>`).join('')}</div>`, 'rooms')}
function render(){const r=route();const map={home,itinerary,budget,food,shopping,resort,traveler,rooms,guide};document.getElementById('app').innerHTML=map[r]();bind(r)}
function bind(r){
  document.getElementById('langBtn')?.addEventListener('click',()=>{state.lang=state.lang==='zh'?'vi':'zh';localStorage.setItem('mtc-lang',state.lang);render()});
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.day);render()});
  document.querySelectorAll('[data-hotel]').forEach(b=>b.onclick=()=>{state.hotel=b.dataset.hotel;render()});
  if(r==='traveler'){document.getElementById('memberSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.getElementById('memberList').innerHTML=memberCards(MEMBERS.filter(m=>`${m.nameZh} ${m.nameEn}`.toLowerCase().includes(q)))})}
  if(r==='guide'){
    document.getElementById('guideSearch')?.addEventListener('input',e=>{state.guideQuery=e.target.value;render()});
    document.querySelectorAll('[data-guide-category]').forEach(b=>b.onclick=()=>{state.guideCategory=b.dataset.guideCategory;render()});
    document.getElementById('guideBack')?.addEventListener('click',()=>{state.guideCategory=null;render()});
    document.querySelectorAll('[data-guide-check]').forEach(c=>c.onchange=()=>localStorage.setItem('guide-check-'+c.dataset.guideCheck,c.checked?'1':'0'));
    document.getElementById('guideReset')?.addEventListener('click',()=>{DIGITAL_GUIDE.sections.checklist.checks.forEach(c=>localStorage.removeItem('guide-check-'+c.id));render()});
    document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>{if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(b.dataset.speak);u.lang=state.lang==='zh'?'zh-TW':'vi-VN';speechSynthesis.speak(u)}});
  }
}
window.addEventListener('hashchange',render);render();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=300').catch(console.warn))}
