import {MEMBERS,ROOMS} from '../data.js';
import {bi} from '../i18n.js';
import {loadLeader,saveLeader,resetLeader,pinHash,isLeaderSession,setLeaderSession,attendanceStatus,setAttendance,qrValue,qrChecked,setQr,exportLeader,validMember} from '../leader-store.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const tabs=()=>`<nav class="leader-tabs">${[['leader','📊','總覽','Tổng quan'],['leader-announcements','📢','公告','Thông báo'],['leader-attendance','✅','點名','Điểm danh'],['leader-qr','▦','QR報到','Check-in QR'],['leader-backup','💾','備份','Sao lưu']].map(x=>`<a href="#/${x[0]}"><span>${x[1]}</span>${bi(x[2],x[3])}</a>`).join('')}</nav>`;
function login(){const data=loadLeader();return `<section class="leader-login card"><span class="leader-shield">🛡️</span><p class="eyebrow">LEADER CENTER</p><h1>${bi('領隊管理中心','Trung tâm trưởng đoàn')}</h1><p>${data.settings.pinConfigured?bi('請輸入領隊PIN。','Nhập PIN trưởng đoàn.'):bi('首次使用請建立4～8位數PIN。','Lần đầu hãy tạo PIN 4–8 chữ số.')}</p><form id="leaderLoginForm"><div class="field"><label>PIN</label><input name="pin" inputmode="numeric" pattern="[0-9]{4,8}" minlength="4" maxlength="8" required></div>${data.settings.pinConfigured?'':`<div class="field"><label>${bi('再次確認PIN','Xác nhận PIN')}</label><input name="confirm" inputmode="numeric" pattern="[0-9]{4,8}" required></div>`}<button class="primary-btn">${bi('登入領隊中心','Đăng nhập')}</button></form><small>${bi('PIN只保存在目前裝置，不代表雲端身分驗證。','PIN chỉ lưu trên thiết bị này, không phải xác thực đám mây.')}</small></section>`}
function shell(content){return `<section class="section leader-title"><div><p class="eyebrow">GN LEADER MODE</p><h1>${bi('領隊管理中心','Trung tâm trưởng đoàn')}</h1></div><button id="leaderLogout" class="secondary-btn">${bi('登出','Đăng xuất')}</button></section>${tabs()}${content}`}
function roomName(member,hotel){const id=member.roomAssignments?.[hotel];return ROOMS.find(room=>room.id===id)?.assignmentCode||id||'—'}
function dashboard(data){const today=data.sessions[0];const present=MEMBERS.filter(m=>attendanceStatus(data,today.id,m.id)==='present').length;const checked=MEMBERS.filter(m=>qrChecked(data,m.id)).length;return shell(`<section class="leader-kpis"><div class="card"><b>${MEMBERS.length}</b><span>${bi('團員','Thành viên')}</span></div><div class="card"><b>${data.announcements.length}</b><span>${bi('自訂公告','Thông báo')}</span></div><div class="card"><b>${present}</b><span>${bi('Day 1已到','Ngày 1 có mặt')}</span></div><div class="card"><b>${checked}</b><span>${bi('QR已報到','Đã check-in QR')}</span></div></section><section class="card section"><h2>${bi('快速管理','Quản lý nhanh')}</h2><div class="leader-action-grid"><a href="#/leader-announcements">📢<b>${bi('發布公告','Đăng thông báo')}</b></a><a href="#/leader-attendance">✅<b>${bi('集合點名','Điểm danh')}</b></a><a href="#/leader-qr">▦<b>${bi('QR報到','Check-in QR')}</b></a><a href="#/leader-backup">💾<b>${bi('匯出備份','Xuất sao lưu')}</b></a></div></section><section class="card section"><h2>${bi('團員資料總覽','Tổng quan thành viên')}</h2><div class="leader-member-table">${MEMBERS.map(m=>`<div><b>${m.number}. ${esc(m.nameZh)}</b><span>✈ ${esc(m.seatOutbound)}／${esc(m.seatReturn)}</span><span>🌺 ${esc(roomName(m,'lexis'))}</span><span>🏨 ${esc(roomName(m,'sunway'))}</span></div>`).join('')}</div></section>`)}
function announcements(data){return shell(`<section class="card section"><h2>${bi('新增公告','Thêm thông báo')}</h2><form id="announcementForm"><div class="grid two"><div class="field"><label>${bi('中文標題','Tiêu đề Hoa')}</label><input name="titleZh" required></div><div class="field"><label>${bi('越文標題','Tiêu đề Việt')}</label><input name="titleVi"></div></div><div class="field"><label>${bi('中文內容','Nội dung Hoa')}</label><textarea name="bodyZh" required></textarea></div><div class="field"><label>${bi('越文內容','Nội dung Việt')}</label><textarea name="bodyVi"></textarea></div><button class="primary-btn">${bi('發布公告','Đăng thông báo')}</button></form></section><section class="section leader-notices">${data.announcements.map(item=>`<article class="card"><small>${esc(item.createdAt.slice(0,16).replace('T',' '))}</small><h3>${esc(bi(item.titleZh,item.titleVi||item.titleZh))}</h3><p>${esc(bi(item.bodyZh,item.bodyVi||item.bodyZh))}</p><button class="danger-link" data-delete-notice="${item.id}">${bi('刪除','Xóa')}</button></article>`).join('')||`<div class="empty">${bi('尚未發布自訂公告','Chưa có thông báo')}</div>`}</section>`)}
function attendance(data){const selected=data.uiSession||data.sessions[0].id;const session=data.sessions.find(x=>x.id===selected)||data.sessions[0];const counts={present:0,late:0,absent:0,pending:0};MEMBERS.forEach(m=>counts[attendanceStatus(data,session.id,m.id)]++);return shell(`<section class="card section"><div class="field"><label>${bi('點名場次','Buổi điểm danh')}</label><select id="attendanceSession">${data.sessions.map(s=>`<option value="${s.id}" ${s.id===session.id?'selected':''}>Day ${s.day} · ${bi(s.titleZh,s.titleVi)}</option>`).join('')}</select></div><div class="leader-counts">${[['present','已到','Có mặt'],['late','遲到','Trễ'],['absent','未到','Vắng'],['pending','未確認','Chưa rõ']].map(x=>`<div><b>${counts[x[0]]}</b><span>${bi(x[1],x[2])}</span></div>`).join('')}</div><button id="allPresent" class="primary-btn">✓ ${bi('全部已到','Tất cả có mặt')}</button></section><section class="leader-attendance-list">${MEMBERS.map(m=>{const status=attendanceStatus(data,session.id,m.id);return `<article class="card"><div><b>${m.number}. ${esc(m.nameZh)}</b><small>${esc(m.nameEn)}</small></div><div>${[['present','✅'],['late','⏰'],['absent','❌'],['pending','○']].map(x=>`<button data-attendance="${m.id}" data-status="${x[0]}" class="${status===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></article>`}).join('')}</section>`)}
function qr(data){const checked=MEMBERS.filter(m=>qrChecked(data,m.id)).length;return shell(`<section class="card section"><h2>${bi('QR／編號報到','Check-in QR / mã số')}</h2><p>${bi('可輸入GN-MY26-M001或直接點選團員完成報到。','Nhập GN-MY26-M001 hoặc chọn thành viên.')}</p><form id="qrForm" class="leader-code-form"><input name="code" placeholder="GN-MY26-M001"><button class="primary-btn">${bi('確認報到','Xác nhận')}</button></form><div class="leader-qr-progress"><b>${checked} / ${MEMBERS.length}</b><span>${bi('已完成報到','đã check-in')}</span></div></section><section class="leader-qr-list">${MEMBERS.map(m=>`<article class="card ${qrChecked(data,m.id)?'checked':''}"><div><b>${m.number}. ${esc(m.nameZh)}</b><small>${qrValue(m)}</small></div><button data-qr-member="${m.id}">${qrChecked(data,m.id)?'↺':'✅'}</button></article>`).join('')}</section>`)}
function backup(data){return shell(`<section class="card section"><h2>${bi('資料備份與重設','Sao lưu và đặt lại')}</h2><p>${bi('備份包含領隊公告、點名、QR報到及PIN設定，不包含旅客護照或身分證資料。','Sao lưu gồm thông báo, điểm danh, QR và cài đặt PIN; không gồm hộ chiếu hoặc ID.')}</p><div class="backup-actions"><button id="leaderExport" class="primary-btn">↓ ${bi('匯出JSON備份','Xuất JSON')}</button><label class="secondary-btn">↑ ${bi('匯入備份','Nhập sao lưu')}<input id="leaderImport" type="file" accept="application/json" hidden></label><button id="leaderReset" class="danger-btn">${bi('重設領隊資料','Đặt lại dữ liệu')}</button></div><small>${bi('最後更新','Cập nhật cuối')}: ${esc(data.updatedAt)}</small></section>`)}
export function leaderPage(route){if(!isLeaderSession())return login();const data=loadLeader();if(route==='leader-announcements')return announcements(data);if(route==='leader-attendance')return attendance(data);if(route==='leader-qr')return qr(data);if(route==='leader-backup')return backup(data);return dashboard(data)}
export function bindLeader(route,render){
 document.querySelector('#leaderLoginForm')?.addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),pin=String(form.get('pin')||''),data=loadLeader();if(!/^\d{4,8}$/.test(pin))return alert(bi('PIN須為4～8位數字','PIN phải có 4–8 số'));if(!data.settings.pinConfigured){if(pin!==String(form.get('confirm')||''))return alert(bi('兩次PIN不一致','PIN không khớp'));data.settings.pinHash=await pinHash(pin);data.settings.pinConfigured=true;saveLeader(data);setLeaderSession(true);render();return}if(await pinHash(pin)!==data.settings.pinHash)return alert(bi('PIN錯誤','PIN sai'));setLeaderSession(true);render()});
 document.querySelector('#leaderLogout')?.addEventListener('click',()=>{setLeaderSession(false);location.hash='#/info'});
 document.querySelector('#announcementForm')?.addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.currentTarget),data=loadLeader();data.announcements.unshift({id:`notice-${Date.now()}`,titleZh:String(f.get('titleZh')),titleVi:String(f.get('titleVi')),bodyZh:String(f.get('bodyZh')),bodyVi:String(f.get('bodyVi')),createdAt:new Date().toISOString()});saveLeader(data);render()});
 document.querySelectorAll('[data-delete-notice]').forEach(button=>button.onclick=()=>{const data=loadLeader();data.announcements=data.announcements.filter(x=>x.id!==button.dataset.deleteNotice);saveLeader(data);render()});
 document.querySelector('#attendanceSession')?.addEventListener('change',event=>{const data=loadLeader();data.uiSession=event.target.value;saveLeader(data);render()});
 document.querySelectorAll('[data-attendance]').forEach(button=>button.onclick=()=>{const data=loadLeader(),sid=data.uiSession||data.sessions[0].id;setAttendance(data,sid,button.dataset.attendance,button.dataset.status);render()});
 document.querySelector('#allPresent')?.addEventListener('click',()=>{let data=loadLeader();const sid=data.uiSession||data.sessions[0].id;MEMBERS.forEach(m=>{data.attendance[sid]??={};data.attendance[sid][m.id]='present'});saveLeader(data);render()});
 document.querySelectorAll('[data-qr-member]').forEach(button=>button.onclick=()=>{const data=loadLeader(),id=button.dataset.qrMember;setQr(data,id,!qrChecked(data,id));render()});
 document.querySelector('#qrForm')?.addEventListener('submit',event=>{event.preventDefault();const code=String(new FormData(event.currentTarget).get('code')||'').trim().toUpperCase(),id=code.replace('GN-MY26-','');if(!validMember(id))return alert(bi('找不到團員編號','Không tìm thấy thành viên'));setQr(loadLeader(),id,true);render()});
 document.querySelector('#leaderExport')?.addEventListener('click',()=>exportLeader(loadLeader()));
 document.querySelector('#leaderImport')?.addEventListener('change',async event=>{try{const parsed=JSON.parse(await event.target.files[0].text());if(!parsed.settings||!Array.isArray(parsed.sessions))throw new Error();saveLeader(parsed);render()}catch{alert(bi('備份格式錯誤','Sai định dạng sao lưu'))}});
 document.querySelector('#leaderReset')?.addEventListener('click',()=>{if(confirm(bi('確定重設全部領隊資料？','Đặt lại toàn bộ dữ liệu?'))){resetLeader();setLeaderSession(false);render()}});
}
